name: Unit Tests with hyperscan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout custom patterns
        uses: actions/checkout@v4

      - name: Checkout secret-scanning-tools
        uses: actions/checkout@v4
        with:
          repository: "advanced-security/secret-scanning-tools"
          path: "secret-scanning-tools"

      - name: Install dependencies
        run: |
          cd "${GITHUB_WORKSPACE}"/secret-scanning-tools/secretscanning
          sudo apt-get -qq update
          sudo apt-get -qq install libpcre3-dev
          python3 -mpip -q install -r requirements.txt
          python3 -mpip -q install tqdm

      - name: Unit Test patterns with hyperscan
        run: |
          cd "${GITHUB_WORKSPACE}"/secret-scanning-tools/secretscanning
          python3 ./test.py --tests "${GITHUB_WORKSPACE}" --exclude django_secret_key
